services:
  postgres:
    container_name: osrsclanmanager_postgres
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    container_name: osrsclanmanager_redis
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redisdata:/data
    env_file:
      - .env

volumes:
  pgdata:
  redisdata:
