services:
  postgres:
    container_name: clan-halls_postgres
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    container_name: clan-halls_redis
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redisdata:/data
    env_file:
      - .env

  backend:
    container_name: clan-halls_backend
    build:
      context: ./backend
    image: clan-halls_backend
    ports:
      - ${BACKEND_PORT}:8000
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
