/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignInImport } from './routes/sign-in'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as OnboardingSyncClanImport } from './routes/onboarding/sync-clan'
import { Route as OnboardingSetUsernameImport } from './routes/onboarding/set-username'
import { Route as OnboardingCreateClanImport } from './routes/onboarding/create-clan'
import { Route as AdminUsersImport } from './routes/admin/users'
import { Route as AdminClansImport } from './routes/admin/clans'

// Create/Update Routes

const SignInRoute = SignInImport.update({
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)

const OnboardingSyncClanRoute = OnboardingSyncClanImport.update({
  path: '/onboarding/sync-clan',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingSetUsernameRoute = OnboardingSetUsernameImport.update({
  path: '/onboarding/set-username',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingCreateClanRoute = OnboardingCreateClanImport.update({
  path: '/onboarding/create-clan',
  getParentRoute: () => rootRoute,
} as any)

const AdminUsersRoute = AdminUsersImport.update({
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)

const AdminClansRoute = AdminClansImport.update({
  path: '/clans',
  getParentRoute: () => AdminRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/admin/clans': {
      id: '/admin/clans'
      path: '/clans'
      fullPath: '/admin/clans'
      preLoaderRoute: typeof AdminClansImport
      parentRoute: typeof AdminImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersImport
      parentRoute: typeof AdminImport
    }
    '/onboarding/create-clan': {
      id: '/onboarding/create-clan'
      path: '/onboarding/create-clan'
      fullPath: '/onboarding/create-clan'
      preLoaderRoute: typeof OnboardingCreateClanImport
      parentRoute: typeof rootRoute
    }
    '/onboarding/set-username': {
      id: '/onboarding/set-username'
      path: '/onboarding/set-username'
      fullPath: '/onboarding/set-username'
      preLoaderRoute: typeof OnboardingSetUsernameImport
      parentRoute: typeof rootRoute
    }
    '/onboarding/sync-clan': {
      id: '/onboarding/sync-clan'
      path: '/onboarding/sync-clan'
      fullPath: '/onboarding/sync-clan'
      preLoaderRoute: typeof OnboardingSyncClanImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AdminRoute: AdminRoute.addChildren({
    AdminClansRoute,
    AdminUsersRoute,
    AdminIndexRoute,
  }),
  SignInRoute,
  OnboardingCreateClanRoute,
  OnboardingSetUsernameRoute,
  OnboardingSyncClanRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/sign-in",
        "/onboarding/create-clan",
        "/onboarding/set-username",
        "/onboarding/sync-clan"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx",
      "children": [
        "/admin/clans",
        "/admin/users",
        "/admin/"
      ]
    },
    "/sign-in": {
      "filePath": "sign-in.tsx"
    },
    "/admin/clans": {
      "filePath": "admin/clans.tsx",
      "parent": "/admin"
    },
    "/admin/users": {
      "filePath": "admin/users.tsx",
      "parent": "/admin"
    },
    "/onboarding/create-clan": {
      "filePath": "onboarding/create-clan.tsx"
    },
    "/onboarding/set-username": {
      "filePath": "onboarding/set-username.tsx"
    },
    "/onboarding/sync-clan": {
      "filePath": "onboarding/sync-clan.tsx"
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    }
  }
}
ROUTE_MANIFEST_END */
