name: 'CI: Lint & Test'

on:
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch: # Allows manual triggering

jobs:
  lint-and-test-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file from secret
        run: echo "${{ secrets.TEST_ENV }}" > .env

      - name: Start Docker containers
        run: docker compose up -d

      - name: Install dependencies
        run: npm ci

      - name: Lint Backend
        run: npm run lint -w backend

      - name: Test Backend
        run: npm run test -w backend

      - name: Lint Frontend
        run: npm run lint -w frontend
