name: "CI: Lint & Test"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file from secret
        run: echo "${{ secrets.TEST_ENV }}" > .env

      - name: Start Docker containers
        run: docker compose -f docker-compose.dev.yml up -d

      - name: Install dependencies
        run: npm ci

      - name: Lint Backend
        run: npm run lint -w backend

      - name: Test Backend
        run: npm run test -w backend

      - name: Lint Frontend
        run: npm run lint -w frontend

      - name: Shutdown Docker containers
        if: always()
        run: docker compose -f docker-compose.dev.yml down || true
