name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: [self-hosted, deploy-backend]

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install global dependencies
        run: npm install -g typescript pm2 typeorm

      - name: Check out the code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref }}

      - name: Set up environment file
        run: echo "${{ secrets.PROD_ENV }}" > .env

      - name: Install dependencies
        run: npm ci

      - name: Build Backend
        run: npm run build -w backend

      - name: Deploy Databases with Docker Compose
        if: success()
        run: docker compose up -d
        working-directory: .

      - name: Make backend script executable
        run: chmod +x ./scripts/prod-backend.sh

      - name: Run Backend Deployment Script
        run: ./scripts/prod-backend.sh
